geometry_msgs/Pose current_pose
---
bool found
asr_msgs/AsrViewport viewport
asr_next_best_view/RobotStateMessage robot_state
# utility
float32 utility
float32 utility_normalization
# total costs
float32 inverse_costs
# specific costs
float32 base_translation_inverse_costs
float32 base_rotation_inverse_costs
float32 ptu_movement_inverse_costs
float32 recognition_inverse_costs